Add AP_Periph MatekL431 CAN Node APD ESC status bitfield
brha8286/ardupilot pull request #1
Opened 2023-09-14 17:30 UTC by brha8286

This adds functionality to receive and parse APD ESC `status` , and then send via dronecan.

The dronecan `esc status` message does not have a `stutus` field.  This uses the `error count` field.

2023-09-14 18:01 UTC, magate commented on Tools/AP_Periph/esc_apd_telem.h
> +            // SKYWAYS start
```suggestion
            // SKYWAYS begin
```

2023-09-14 18:01 UTC, magate commented on Tools/AP_Periph/esc_apd_telem.cpp
> +                    // SKYWAYS start
```suggestion
                    // SKYWAYS begin
```

2023-09-14 18:03 UTC, magate commented on Tools/AP_Periph/esc_apd_telem.cpp
> +                    decoded.error_count = le32toh(received.packet.status_flags);
Won't you need to create a `le8toh` here? https://github.com/brha8286/ardupilot/blob/ac42f5fb5ebf7e6daaaa8b5964b7f8c13fa43f19/libraries/AP_HAL/utility/sparse-endian.h#L84

2023-09-14 18:05 UTC, magate commented on Tools/AP_Periph/esc_apd_telem.cpp
> +                    decoded.error_count = le32toh(received.packet.status_flags);
And then I think you're going to have problems packing that into a `uint32`? Do we have to hijack the message like this?

2023-09-14 18:05 UTC, magate requested changes
I'm thinking making this compatible with upstream is the way to go. I'll chew on it a bit more.

2023-09-14 20:21 UTC, magate commented
Lets put this here: https://github.com/skywaysinc/ardupilot-skyways/tree/AP_Periph-1.6

2026-03-17 17:20 UTC, brha8286 commented
Closing stale PR — over 2 years old.

2026-03-17 17:20 UTC, closed without merging